const mongoose = require("mongoose");
const { Restaurants, Tables, Products } = require("./app/db/models");

const dummyProducts = [{
  "recipe": [],
  "name": "Espresso",
  "description": "",
  "qty": "",
  "currency": "RON",
  "price": "",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Coffee",
  "subCategory": ""
},
{
  "name": "Espresso scurt",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Espresso Lung",
  "qty": "45",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},

{
  "recipe": [],
  "name": "Espresso Doppio",
  "description": "",
  "qty": "60",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "16",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Coffee",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Cafea fara cofeina",
  "description": "",
  "qty": "45",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Coffee",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Espresso Freddo",
  "description": "",
  "qty": "45",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Coffee",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Cappuccino",
  "description": "",
  "qty": "100",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Coffee",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Cappucino Freddo",
  "description": "",
  "qty": "100",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "14",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Coffee",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Caffee Latte",
  "description": "",
  "qty": "150",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Coffee",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Latte Machiatto",
  "description": "",
  "qty": "150",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "14",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Coffee",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Caffee Coretto",
  "description": "",
  "qty": "100",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Coffee",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Irish Coffee",
  "description": "espresso, irish whisky, frisca",
  "qty": "100",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Coffee",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Irish Cream Coffee",
  "description": "espresso, baileys, frisca",
  "qty": "100",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Coffee",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Frappe",
  "description": "cafea instant, zahar,lapte, frisca",
  "qty": "150",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Coffee",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Lapte cald cu miere",
  "description": "",
  "qty": "150",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Milky Drinks",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Lapte cu cacao",
  "description": "",
  "qty": "150",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Milky Drinks",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Ciocolata Calda",
  "description": "",
  "qty": "",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Milky Drinks",
  "subCategory": ""
},
{
  "name": "Ciocolata Calda Alba",
  "qty": "150",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "16",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Ciocolata Calda Neagra",
  "qty": "150",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "16",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Tea Forte",
  "description": "Classic Collection",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "recipe": [],
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Ceai"
},
{
  "name": "Earl Grey",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "White Ginger Pear",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Raspberry Nectar",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Moroccan Mint",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Strawberry Hibiscus",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "recipe": [],
  "name": "Ciacotea",
  "description": "Ceai verde cu iasomie sfere mici.",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Ceai",
  "subCategory": ""
},
{
  "name": "Flavoured Iced Tea",
  "description": "capsuni, pepene rosu, pepene galben, ananas",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "recipe": [],
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Ceai"
},
{
  "name": "Capsuni ",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Pepene Rosu",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Pepene Galben",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Ananas",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Fara Arome",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "recipe": [],
  "name": "Ceai preparat fara alcool",
  "description": "Ceai infuzie, sirop infuzat cu condimente, suc lamaie, portocala, ananas, cireasa maraschino.",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Ceai",
  "subCategory": ""
},
{
  "name": "Ceai RockNRolla",
  "description": "Ceai infuzie, sirop infuzat cu condimente, suc lamaie, portocala, ananas, cireasa maraschino, Tatratea, Rom sau Le Birlou",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "recipe": [],
  "stock": 1000,
  "active": true,
  "alcoholContent": "~% vol",
  "type": "variation",
  "category": "Ceai"
},
{
  "name": "RockNRolla + Tatratea",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "~5% vol",
  "type": "recipeProduct",
},
{
  "name": "RockNrolla + Rom",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "~5% vol",
  "type": "recipeProduct",
},
{
  "name": "RockNRolla + Le Birlou",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "6% vol",
  "type": "recipeProduct",
},
{
  "name": "Pepsi",
  "description": "",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "recipe": [],
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Softies"
},
{
  "name": "Pepsi Regular",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Pepsi Black",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},

{
  "recipe": [],
  "name": "7UP",
  "description": "",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Softies",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Curiousity Cola",
  "description": "Fentimans",
  "qty": "275",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Softies",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Apa Tonica",
  "description": "Fentimans",
  "qty": "330",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Softies",
  "subCategory": ""
},
{
  "name": "Mellow",
  "description": "",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "recipe": [],
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Softies"
},
{
  "name": "Mellow Orange",
  "qty": "330",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Mellow Mango",
  "qty": "330",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Mellow Apple",
  "qty": "330",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "recipe": [],
  "name": "Apa Tonica",
  "description": "Fentimans",
  "qty": "330",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Softies",
  "subCategory": ""
},
{
  "name": "Santal",
  "description": "",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "recipe": [],
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Softies"
},
{
  "name": "Santal Portocale",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Santal Cranberries",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "recipe": [],
  "name": "Aloe Vera Natural",
  "description": "",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Softies",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Suc de rosii",
  "description": "",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Softies",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Red Bull",
  "description": "",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Softies",
  "subCategory": ""
},
{
  "name": "Apa Bucovina",
  "description": "",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "recipe": [],
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Softies"
},
{
  "name": "Minerala",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "8",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Plata",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "8",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Lemonade",
  "description": "suc lamaie, sirop zahar sau miere, apa plata",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "recipe": [],
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Soft On Rocks"
},
{
  "name": "Lemonade cu miere ",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Lemonade cu sirop de zahar",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Lemonade neindulcita",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Flavoured Lemonade",
  "description": "capsuni, pepene rosu, pepene galben, ananas",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "recipe": [],
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Soft On Rocks"
},
{
  "name": "Capsuni ",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Pepene Rosu",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Pepene Galben",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Ananas",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Fresh",
  "description": "portocale | grapefruit | mix",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "recipe": [],
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Soft On Rocks"
},
{
  "name": "Portocale",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Grapefruit",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Mix",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "recipe": [],
  "name": "Virgin Bloody Mary",
  "description": "suc rosii, sare, piper, tabasco, worchestershire sauce",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "NA Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Watermelon Slap",
  "description": "lime, sirop zahar,pepene rosu, aloe vera",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "NA Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Melon Slap",
  "description": "lime, sirop zahar, pepene galben, aloe vera",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "NA Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Yellow Jacket",
  "description": "suc de lamaie, sirop de zahar, piure de ananas, Aloe vera",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "NA Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "RockNRolla",
  "description": "rom alb, cointreau, rodie, suc lamaie, sirop de zahar condimentat",
  "qty": "100",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "29",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Pink Floyd",
  "description": "Gin, Cointreau, bitter portocale, suc lamaie, sirop de zahar",
  "qty": "100",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "29",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Cosmopolitan",
  "description": "Vodka, triple sec, suc merisoare, suc lime",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "27",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Long Island Iced Tea",
  "description": "Vodka, gin, rom alb, tequila, triple sec, suc lamaie, splash cola",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "28",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Mai Tai",
  "description": "Rom alb, Rom negru, amaretto, suc lamaie, sirop zahar, Angostura bitter",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "29",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Cherry Lady",
  "description": "suc lamaie, coriander syrup, gin, maraschino, greeen chartereuse, angostura bitter, maraschino cherry",
  "qty": "100",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "30",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Vodka Sour",
  "description": "vodka, suc lamaie, sirop zahar, aloe vera",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "27",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Rum Sour",
  "description": "Rum Anejo, suc lamaie, sirop zahar, aloe vera",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "27",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Whiskey Sour",
  "description": "Bourbon, suc lamaie, Angostura Bitter",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "27",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Manhattan",
  "description": "Bulleit rye, red vermouth, angostura bitter, cherry",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "30",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "White Cuban",
  "description": "Spiced rum, kahlua, whipped cream, piscot",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "28",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Witches Lemonade",
  "description": "peachtree, maraschino, vodka, suc lamaie, sirop amarena",
  "qty": "100",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "32",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Godfather",
  "description": "Whiskey, Amaretto",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "27",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Godmother",
  "description": "Vodaka, Amaretto",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "27",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Negroni",
  "description": "Whiskey, Amaretto",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "27",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Bloody Mary",
  "description": "Vodka, suc rosii, tabasco, worchestershire sauce, sare, piper",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "27",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Black Russian",
  "description": "vodka, kalhua",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "22",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "White Russian",
  "description": "vodka, kalhua, frisca lichida",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "22",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Aperol Spritz",
  "description": "Aperol, Prosecco, sifon",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "27",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Campari Orange",
  "description": "Campari, suc portocale",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "23",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Long Drinks",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Campari Tonic",
  "description": "Campari, apa tonica",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "23",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Long Drinks",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Campari Soda",
  "description": "Campari, sifon",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "23",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Long Drinks",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Old Fashioned",
  "description": "Bulleit rye, winter sugar syrup, angostura orange, orange peel",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "30",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Boulevardier",
  "description": "bourbon, campari, red vermouth",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "27",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Cocktails",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Caipiroska",
  "description": "lime, zahar, vodka",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "27",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Caipis",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Caipirissima",
  "description": "lime, zahar, rom alb",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "27",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Caipis",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Mojito",
  "description": "lime zahar, menta rom alb",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "28",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Caipis",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Screwdriver",
  "description": "vodka, suc portocale",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Long Drinks",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Cuba Libre",
  "description": "rom, cola, lime",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Long Drinks",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Cape Code",
  "description": "vodka, suc merisoare, lime",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "23",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Long Drinks",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Gin Tonic",
  "description": "vodka, suc portocale",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "23",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Long Drinks",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Whiskey Cola",
  "description": "whiskey, cola",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "23",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Long Drinks",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Cuba Libre - Pitcher",
  "description": "rom, cola, lime, galeata",
  "qty": "1000",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "80",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Long Drinks",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Screwdriver",
  "description": "vodka, suc portocale",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "23",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Long Drinks",
  "subCategory": ""
},
{
  "name": "Somersby",
  "description": "Apple | Pear | Blackberry | Blueberry",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "recipe": [],
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Cider"
},
{
  "name": "Somersby Apple",
  "qty": "330",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Somersby Pear",
  "qty": "330",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Somersby Blackberry",
  "qty": "330",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Somersby Blueberry",
  "qty": "330",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "recipe": [],
  "name": "Alune Prajite",
  "description": "",
  "qty": "150",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Snacks",
  "subCategory": ""
},
{
  "name": "Nachos",
  "description": "Mare | Mic",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "recipe": [],
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Snacks"
},
{
  "name": "Nachos Mare",
  "qty": "100",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "23",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Nachos Mic",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "recipe": [],
  "name": "Masline",
  "description": "",
  "qty": "150",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Snacks",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Irish Shot",
  "description": "Irish whiskey, Baileys, Guinness",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Flower Shot",
  "description": "tatratea, aperol, suc lamaie, sirop zahar infuzat cu condimente",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "B52",
  "description": "",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Whiskey",
  "description": "",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Iced Shot",
  "description": "shot din gheata",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Patron",
  "description": "",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Mezcal Monte Albano",
  "description": "",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Kamikaze",
  "description": "",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "9",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Jagermeister",
  "description": "",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Jagertee Stroh",
  "description": "",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Vodka",
  "description": "",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Tequila Jose Cuervo",
  "description": "",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "name": "Tequila Lunazul",
  "description": "reposado | blanco",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "recipe": [],
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Shots"
},
{
  "name": "Tequila Lunazul reposado",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Tequila Lunazul blanco",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Tatratea",
  "description": "52 | 62 | 72",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "recipe": [],
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Shots"
},
{
  "name": "Tatratea 52",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Tatratea 62",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Tatratea 72",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "recipe": [],
  "name": "Campari",
  "description": "",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Jagerbomb",
  "description": "",
  "qty": "",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "17",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Cherry Lady",
  "description": "",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Pernod Absinthe",
  "description": "",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Rusty Nail",
  "description": "",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "10",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Red Sniper",
  "description": "picant",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Shots",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Spitfire",
  "description": "Amber Ale",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "25",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "4.5% vol",
  "type": "product",
  "category": "Special Beers",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Bishops Finger",
  "description": "Amber Ale",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "25",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5.4% vol",
  "type": "product",
  "category": "Special Beers",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Hobgoblin",
  "description": "Amber Ale",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "23",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5.2% vol",
  "type": "product",
  "category": "Special Beers",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Hobgoblin IPA",
  "description": "Amber IPA",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "25",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5.3% vol",
  "type": "product",
  "category": "Special Beers",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "London Pride Original Ale",
  "description": "Fullers's",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "25",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "4.1% vol",
  "type": "product",
  "category": "Special Beers",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Golden Pride",
  "description": "Amber Ale",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "25",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "8.5% vol",
  "type": "product",
  "category": "Special Beers",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "London Porter",
  "description": "Stout",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "25",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5.4% vol",
  "type": "product",
  "category": "Special Beers",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Crowd Control",
  "description": "HopHooligans",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "28",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "6% vol",
  "type": "product",
  "category": "Special Beers",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Summer Punch",
  "description": "",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "25",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": false,
  "alcoholContent": "4.5 vol",
  "type": "product",
  "category": "Special Beers",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Nemteana Aramie",
  "description": "",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "6.5% vol",
  "type": "product",
  "category": "Special Beers",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Corona",
  "description": "",
  "qty": "355",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "17",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "4.5 vol",
  "type": "product",
  "category": "Special Beers",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Bavaria Claro",
  "description": "",
  "qty": "330",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5% vol",
  "type": "product",
  "category": "Special Beers",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Bernard Celebration Lager",
  "description": "",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "25",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5% vol",
  "type": "product",
  "category": "Special Beers",
  "subCategory": ""
},
{
  "recipe": [],
  "name": "Guinness",
  "description": "",
  "qty": "",
  "currency": "RON",
  "price": "",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Beer",
  "subCategory": "Draught"
},
{
  "name": "Guinness Mic",
  "qty": "250",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "14",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "4.2% vol",
  "type": "recipeProduct",
},
{
  "name": "Guinness Mare",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "28",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "4.2% vol",
  "type": "recipeProduct",
},
{
  "recipe": [],
  "name": "Carlsberg",
  "description": "",
  "qty": "400",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5.2% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Draught"
},
{
  "recipe": [],
  "name": "Carlsberg Luma",
  "description": "",
  "qty": "400",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5.2% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Draught"
},
{
  "recipe": [],
  "name": "Tuborg",
  "description": "",
  "qty": "400",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "13",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Draught"
},
{
  "recipe": [],
  "name": "Holsten Wheat",
  "description": "",
  "qty": "400",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "4.6% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Draught"
},
{
  "recipe": [],
  "name": "Tuborg - Tower",
  "description": "",
  "qty": "2500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "80",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Draught"
},
{
  "recipe": [],
  "name": "Carlsberg - Tower",
  "description": "",
  "qty": "3000",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "110",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5.2% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Draught"
},
{
  "recipe": [],
  "name": "Holsten Wheat - Tower",
  "description": "",
  "qty": "3000",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "120",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "4.6% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Draught"
},
{
  "recipe": [],
  "name": "Carlsberg",
  "description": "",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "13",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5.2% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Bottled"
},
{
  "recipe": [],
  "name": "Tuborg",
  "description": "",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "11",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5.0% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Bottled"
},
{
  "recipe": [],
  "name": "Holsten Wheat",
  "description": "",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5.4% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Bottled"
},
{
  "recipe": [],
  "name": "Holsten Radler",
  "description": "",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5.4% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Bottled"
},
{
  "recipe": [],
  "name": "Csiki Sor Gold",
  "description": "",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "6% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Bottled"
},
{
  "recipe": [],
  "name": "Bucur Bruna",
  "description": "",
  "qty": "350",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "14",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "6.5% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Bottled"
},
{
  "recipe": [],
  "name": "Bucur Blonda",
  "description": "",
  "qty": "350",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Bottled"
},
{
  "recipe": [],
  "name": "Kronenbourg 1664 Blanc",
  "description": "",
  "qty": "330",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Bottled"
},
{
  "recipe": [],
  "name": "Grimbergen Ambre",
  "description": "",
  "qty": "330",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "6.5% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Bottled"
},
{
  "recipe": [],
  "name": "Weihenstephaner Hefe Weissbier",
  "description": "",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "22",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "5.4% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Bottled"
},
{
  "recipe": [],
  "name": "Tuborg N.A.",
  "description": "",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "0% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Bottled"
},
{
  "recipe": [],
  "name": "Carlsberg N.A.",
  "description": "",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "0% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Bottled"
},
{
  "recipe": [],
  "name": "Holsten Radler",
  "description": "",
  "qty": "500",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "12",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "0% vol",
  "type": "product",
  "category": "Beer",
  "subCategory": "Bottled"
},
{
  "recipe": [],
  "name": "Budureasca",
  "description": "",
  "qty": "",
  "currency": "RON",
  "price": "",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Wine",
  "subCategory": "Pahar"
},
{
  "name": "Alb",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "14",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Roze",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "14",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "name": "Rosu",
  "qty": "30",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "14",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "recipeProduct",
},
{
  "recipe": [],
  "name": "Zgihara de Averesti",
  "description": "alb sec",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "25",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "Pahar"
},
{
  "recipe": [],
  "name": "Busuioaca de Averesti",
  "description": "roze sec",
  "qty": "200",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "25",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "Pahar"
},
{
  "recipe": [],
  "name": "Purcari Pinot Grigio",
  "description": "SEC",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "110",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "ALB"
},
{
  "recipe": [],
  "name": "Purcari Nocturne - Chardonnay",
  "description": "SEC",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "110",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "ALB"
},
{
  "recipe": [],
  "name": "Purcari Nocturne - Sauvignon Blanc",
  "description": "SEC",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "110",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "ALB"
},
{
  "recipe": [],
  "name": "Zghihara de averesti",
  "description": "SEC",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "110",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "ALB"
},
{
  "recipe": [],
  "name": "Purcari Chardonnay",
  "description": "SEC",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "100",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "ALB"
},
{
  "recipe": [],
  "name": "Busuioaca de Averesti",
  "description": "SEC",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "110",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "ROZE"
},
{
  "recipe": [],
  "name": "Feteasca neagra de Averesti",
  "description": "SEC",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "100",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "ROSU"
},
{
  "recipe": [],
  "name": "Purcari Merlot",
  "description": "SEC",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "100",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "ROSU"
},
{
  "recipe": [],
  "name": "Purcari Rara Neagra",
  "description": "SEC",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "100",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "ROSU"
},
{
  "recipe": [],
  "name": "Via Marchizului Negru de Dragasani",
  "description": "SEC",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "120",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "ROSU"
},
{
  "recipe": [],
  "name": "Recas Selene Syrah",
  "description": "SEC",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "130",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "ROSU"
},
{
  "recipe": [],
  "name": "Cantus Primus Dealul Mare",
  "description": "SEC",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "135",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "ROSU"
},
{
  "recipe": [],
  "name": "Gitana Autograf Merlot",
  "description": "SEC",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "120",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "ROSU"
},
{
  "recipe": [],
  "name": "Moet & Chandon Brut",
  "description": "BRUT",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "400",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "product",
  "category": "Wine",
  "subCategory": "SPARKLING"
},
{
  "recipe": [],
  "name": "Prosecco",
  "description": "BRUT",
  "qty": "750",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "130",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "11% vol",
  "type": "product",
  "category": "Wine",
  "subCategory": "SPARKLING"
},
{
  "recipe": [],
  "name": "Glen Scotia Victoriana",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "35",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "54.2% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "SINGLE MALT SCOTCH"
},
{
  "recipe": [],
  "name": "Glen Scotia Double Cask",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "25",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "46% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "SINGLE MALT SCOTCH"
},
{
  "recipe": [],
  "name": "Glen Moray",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "22",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "43% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "SINGLE MALT SCOTCH"
},
{
  "recipe": [],
  "name": "Glenfiddich 12 Y.O",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "28",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "SINGLE MALT SCOTCH"
},
{
  "recipe": [],
  "name": "Lagavulin",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "40",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "43% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "SINGLE MALT SCOTCH"
},
{
  "recipe": [],
  "name": "Smokehead",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "40",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "43% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "SINGLE MALT SCOTCH"
},
{
  "recipe": [],
  "name": "Macallan",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "55",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "SINGLE MALT SCOTCH"
},
{
  "recipe": [],
  "name": "Nikka Coffee Malt",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "22",
  "imgUrl": "45",
  "stock": 1000,
  "active": true,
  "alcoholContent": "43% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "SINGLE MALT SCOTCH"
},
{
  "recipe": [],
  "name": "Glenlivet 18 Y.O",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "40",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "SINGLE MALT SCOTCH"
},
{
  "recipe": [],
  "name": "Laphroaig 10 Y.O",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "30",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "48% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "SINGLE MALT SCOTCH"
},
{
  "recipe": [],
  "name": "Talisker 10 Y.O",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "30",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "45.8% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "SINGLE MALT SCOTCH"
},
{
  "recipe": [],
  "name": "Johnnie Walker Red Label",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "BLENDED SCOTCH"
},
{
  "recipe": [],
  "name": "Johnnie Walker Black Label 12 Y.O",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "BLENDED SCOTCH"
},
{
  "recipe": [],
  "name": "CuttySark Prohibition",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "BLENDED SCOTCH"
},
{
  "recipe": [],
  "name": "Chivas Regal 12 Y.O",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "BLENDED SCOTCH"
},
{
  "recipe": [],
  "name": "Famouse Grouse",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "BLENDED SCOTCH"
},
{
  "recipe": [],
  "name": "Tullamore Dew 12 Y.O",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "IRISH WHISKEY"
},
{
  "recipe": [],
  "name": "Jameson",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "IRISH WHISKEY"
},
{
  "recipe": [],
  "name": "Jameson Black Barrell",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "IRISH WHISKEY"
},
{
  "recipe": [],
  "name": "Bushmills 10 Y.O",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "IRISH WHISKEY"
},
{
  "recipe": [],
  "name": "Bushmills 10 Y.O Cherry Cask",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "24",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "46% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "IRISH WHISKEY"
},
{
  "recipe": [],
  "name": "Rittenhouse",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "24",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "50% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "AMERICAN WHISKEY"
},
{
  "recipe": [],
  "name": "Elijah Craig Small Batch",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "26",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "47% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "AMERICAN WHISKEY"
},
{
  "recipe": [],
  "name": "Woodford Reserve",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "24",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "43.2% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "AMERICAN WHISKEY"
},
{
  "recipe": [],
  "name": "Wild Turkey 101",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "AMERICAN WHISKEY"
},
{
  "recipe": [],
  "name": "Jack Daniel's Old Nr. 7",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "AMERICAN WHISKEY"
},
{
  "recipe": [],
  "name": "Jim Beam",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "AMERICAN WHISKEY"
},
{
  "recipe": [],
  "name": "Courvoisier V.S.",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "24",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "COGNAC & BRANDY"
},
{
  "recipe": [],
  "name": "Metaxa 5*",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "COGNAC & BRANDY"
},
{
  "recipe": [],
  "name": "Hennessy",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "24",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "COGNAC & BRANDY"
},
{
  "recipe": [],
  "name": "Grey Goose",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "24",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "VODKA"
},
{
  "recipe": [],
  "name": "Stalinskaya Gold",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "VODKA"
},
{
  "recipe": [],
  "name": "Stolichnaya Cristall",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "17",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "VODKA"
},
{
  "recipe": [],
  "name": "Tito's Handmade",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "17",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "VODKA"
},
{
  "recipe": [],
  "name": "Absolut",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "VODKA"
},
{
  "recipe": [],
  "name": "Finlandia",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "VODKA"
},
{
  "recipe": [],
  "name": "Stolichnaya",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "14",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "VODKA"
},
{
  "recipe": [],
  "name": "Monkey 47",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "28",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "41.3% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "GIN"
},
{
  "recipe": [],
  "name": "Chartuse Green",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "55% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "GIN"
},
{
  "recipe": [],
  "name": "Hendricks's",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "41.3% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "GIN"
},
{
  "recipe": [],
  "name": "Wembley Crown",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "GIN"
},
{
  "recipe": [],
  "name": "Whitley Neil Quice Gin",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "43% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "GIN"
},
{
  "recipe": [],
  "name": "Citadelle",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "44% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "GIN"
},
{
  "recipe": [],
  "name": "Tanqueray",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "18",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "43.1% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "GIN"
},
{
  "recipe": [],
  "name": "Wembley Dry Gin",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "14",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "GIN"
},
{
  "recipe": [],
  "name": "Campari",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "25% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "VERMOUTH & BITTER"
},
{
  "recipe": [],
  "name": "Aperol",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "11% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "VERMOUTH & BITTER"
},
{
  "recipe": [],
  "name": "Jagermeister",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "35% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "VERMOUTH & BITTER"
},
{
  "recipe": [],
  "name": "Fernet Branca",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "25% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "VERMOUTH & BITTER"
},
{
  "recipe": [],
  "name": "Martini",
  "description": "",
  "qty": "",
  "currency": "RON",
  "price": "",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "",
  "type": "variation",
  "category": "Spirits",
  "subCategory": "VERMOUTH & BITTER"
},
{
  "name": "Bianco",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "recipeProduct",
},
{
  "name": "Rosso",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "recipeProduct",
},
{
  "recipe": [],
  "name": "Kahlua",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "14",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "17% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "LIQUEURS"
},
{
  "recipe": [],
  "name": "Amaretto Rose Mary",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "14",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "20% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "LIQUEURS"
},
{
  "recipe": [],
  "name": "Southern Comfort",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "38% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "LIQUEURS"
},
{
  "recipe": [],
  "name": "Cointreau",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "17% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "LIQUEURS"
},
{
  "recipe": [],
  "name": "Bailey's",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "LIQUEURS"
},
{
  "recipe": [],
  "name": "Chartruse",
  "description": "Green",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "55% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "LIQUEURS"
},
{
  "recipe": [],
  "name": "Diplomatico Reserva Exclusiva",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "24",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "38% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "RUM"
},
{
  "recipe": [],
  "name": "The Duppy Share X.O",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "RUM"
},
{
  "recipe": [],
  "name": "The Duppy Share Spiced",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "37.5% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "RUM"
},
{
  "recipe": [],
  "name": "Plantation Original Dark",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "17",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "RUM"
},
{
  "recipe": [],
  "name": "Flor de Cana 18 Y.O",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "24",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "RUM"
},
{
  "recipe": [],
  "name": "Plantation Pineapple",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "RUM"
},
{
  "recipe": [],
  "name": "Plantation 3*",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": false,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "RUM"
},
{
  "recipe": [],
  "name": "Havana 7 Y.O",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "20",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "RUM"
},
{
  "recipe": [],
  "name": "Cubay Anejo",
  "description": "",
  "qty": "50",
  "measureUnit": "ml",
  "currency": "RON",
  "price": "15",
  "imgUrl": "https://rocknrolla.ro/images/rnr-placeholder.jpg",
  "stock": 1000,
  "active": true,
  "alcoholContent": "40% vol",
  "type": "product",
  "category": "Spirits",
  "subCategory": "RUM"
}
];

const restaurant = new Restaurants({
  _id: '641ef47dd6a1260012acd8c7',
  name: "NotRocknRolla",
  ownerName: "Pablo e Sobar"
});

(async () => {
  try {

    await mongoose.connect(`mongodb://${process.env.MONGODB_HOST || 'localhost'}/tabley?retryWrites=true&w=majority`, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    const restaurantDetails = await restaurant.save();
    delete restaurantDetails.__v;
    console.log("/////////////////////////////////////////");
    console.log("/////////////////////////////////////////");
    console.log("/////////////////////////////////////////");
    console.log(restaurantDetails);
    console.log("/////////////////////////////////////////");
    console.log("/////////////////////////////////////////");
    console.log("/////////////////////////////////////////");

    for (let i = 1; i <= 20; i++) {
      await new Tables({
        restaurantId: restaurantDetails._id,
        tableNo: i
      }).save();
      console.log(`Added table nr ${i}`);
    }


    await dummyProducts.map(async (dummyProduct) => {
      const newDummyProduct = new Products({
        ...dummyProduct,
        restaurantId: restaurantDetails._id
      })
      await newDummyProduct.save();
      console.log(`Added product (${dummyProduct.category}) ${dummyProduct.name}`)
    });

    console.log("Done!");

  } catch (e) {
    console.log(e);
  }

})();